services:
  # Use pre-built OvenMediaEngine directly (fastest deployment)
  origin:
    image: airensoft/ovenmediaengine:latest
    container_name: cruvz-streaming-origin
    restart: always
    ports:
      - "1935:1935"     # RTMP
      - "3333:3333"     # WebRTC/LLHLS  
      - "9999:9999/udp" # SRT
      - "8080:8080"     # API
    volumes:
      - ./misc/conf_examples/Origin.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml:ro
      - ./misc/conf_examples/Logger.xml:/opt/ovenmediaengine/bin/origin_conf/Logger.xml:ro
    networks:
      - cruvz-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f OvenMediaEngine > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Backend with production-ready setup  
  backend:
    image: node:18-slim
    container_name: cruvz-streaming-backend
    restart: always
    working_dir: /app
    command: sh -c "npm install --production --no-audit --no-fund && node server.js"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=./data/cruvz_streaming.db
      - JWT_SECRET=cruvz-streaming-production-secret-2024
      - FRONTEND_URL=http://localhost
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    networks:
      - cruvz-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Web Application
  web-app:
    image: nginx:alpine
    container_name: cruvz-streaming-webapp
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./web-app:/usr/share/nginx/html:ro
      - ./web-app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cruvz-network
    depends_on:
      - backend
      - origin

volumes:
  backend-data:
    driver: local

networks:
  cruvz-network:
    driver: bridge