# Prometheus configuration for Cruvz Streaming Six Sigma monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cruvz-streaming-origin'
    static_configs:
      - targets: ['origin:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'cruvz-streaming-edge'
    static_configs:
      - targets: ['edge:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093