apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cruvz-srt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cruvz-secrets
              key: REDIS_PASSWORD
              optional: true
        command: ["/bin/sh"]
        args:
        - -c
        - |
          if [ -z "$REDIS_PASSWORD" ]; then
            exec redis-server \
              --save "900 1" \
              --save "300 10" \
              --save "60 10000" \
              --loglevel warning \
              --maxmemory 256mb \
              --maxmemory-policy allkeys-lru \
              --tcp-keepalive 300 \
              --timeout 0 \
              --databases 16 \
              --no-auth-warning
          else
            exec redis-server \
              --save "900 1" \
              --save "300 10" \
              --save "60 10000" \
              --loglevel warning \
              --maxmemory 256mb \
              --maxmemory-policy allkeys-lru \
              --requirepass "$REDIS_PASSWORD" \
              --tcp-keepalive 300 \
              --timeout 0 \
              --databases 16
          fi
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              if [ -z "$REDIS_PASSWORD" ]; then
                redis-cli ping | grep PONG
              else
                redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
              fi
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - |
              if [ -z "$REDIS_PASSWORD" ]; then
                redis-cli ping | grep PONG
              else
                redis-cli -a "$REDIS_PASSWORD" ping | grep PONG
              fi
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cruvz-srt
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: cruvz-srt
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
