apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cruvz-srt-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  # Production-ready storage parameters
  fsType: ext4

---
# Production PersistentVolume for Redis with proper node affinity
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: local
    app: redis
    tier: cache
spec:
  storageClassName: cruvz-srt-storage
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/cruvz-srt/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # Replace with actual node name
          - master # Alternative node name

---
# Production PersistentVolume for PostgreSQL with proper node affinity
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
    tier: database
spec:
  storageClassName: cruvz-srt-storage
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/cruvz-srt/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # Replace with actual node name
          - master # Alternative node name

---
# Production PersistentVolume for Backend uploads
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-uploads-pv
  labels:
    type: local
    app: backend
    tier: application
spec:
  storageClassName: cruvz-srt-storage
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/cruvz-srt/uploads
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # Replace with actual node name
          - master # Alternative node name

---
# Production PersistentVolume for OvenMediaEngine recordings
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ome-recordings-pv
  labels:
    type: local
    app: ovenmediaengine
    tier: streaming
spec:
  storageClassName: cruvz-srt-storage
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/cruvz-srt/recordings
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1  # Replace with actual node name
          - master # Alternative node name
