apiVersion: 1

# Six Sigma Data Sources Configuration
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: GET
      
  - name: Loki
    type: loki
    access: proxy
    url: http://log-aggregator:3100
    editable: true
    jsonData:
      maxLines: 1000
      
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true